spring.profiles.active: development
---
spring:
  profiles: development
  data:
    rest:
      base-path: /api
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: secret
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.10.200:8761/eureka/