spring:
  profiles:
    active: development
---
spring:
  profiles: development
  redis:
    host: 192.168.10.200
    port: 6379
  jpa:
    show-sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://192.168.10.200:3306/dev?useSSL=false
    username: root
    password: dbpass